# Generated by Django 4.0.1 on 2023-05-22 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('CREATOR', 'CREATOR'), ('PARTICIPANT', 'PARTICIPANT')], max_length=20)),
                ('birth_date', models.DateField(blank=True, default=None)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(choices=[('SCHOOL5', 'SCHOOL5'), ('SCHOOL9', 'SCHOOL9'), ('SCHOOL11', 'SCHOOL11'), ('UNI1', 'UNI1'), ('UNI4', 'UNI4'), ('NO', 'NO')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='OlympiadUse_user_id_c0abcb_idx'),
        ),
    ]
