# Generated by Django 4.0.1 on 2023-05-14 14:19

import OlympiadMainApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('testinput', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Текстовый ввод')),
                ('testoutput', models.CharField(max_length=1000, verbose_name='Текстовый вывод')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название задачи')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание задачи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('olympiad', models.CharField(max_length=255, verbose_name='Название олимпиады')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Очки пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, default=None)),
                ('region', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название задачи')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание задачи')),
                ('points', models.PositiveSmallIntegerField(default=10, verbose_name='Очки')),
                ('tests', djongo.models.fields.ArrayField(default=None, model_container=OlympiadMainApp.models.TestData, verbose_name='Тестовые данные')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('until', models.DateTimeField(default=None, verbose_name='Активна до')),
                ('active', models.BooleanField(default=True)),
                ('olympiadname', models.CharField(default=None, max_length=255, verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('taskname', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Очки пользователя')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='taskresult',
            index=models.Index(fields=['uname'], name='res_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taskresult',
            index=models.Index(fields=['taskname'], name='res_task_idx'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='results',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='OlympiadMainApp.taskresult', verbose_name='Результаты пользователей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='olympiads_results',
            field=djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='OlympiadMainApp.olympiadresult', verbose_name='Результаты олимпиад'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks_results',
            field=djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='OlympiadMainApp.taskresult', verbose_name='Результаты задач'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='olympiadresult',
            index=models.Index(fields=['uname'], name='olympres_name_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadresult',
            index=models.Index(fields=['olympiad'], name='olympres_olymp_idx'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='results',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='olympres', to='OlympiadMainApp.olympiadresult', verbose_name='Результаты пользователей'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='tasks',
            field=djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='OlympiadMainApp.task', verbose_name='Результаты пользователей'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name'], name='OlympiadMai_name_36b787_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='OlympiadMai_user_id_7aa9df_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['name'], name='OlympiadMai_name_3ff5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['created'], name='olymp_created_idx'),
        ),
    ]
