# Generated by Django 4.0.1 on 2023-06-02 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OlympiadMainApp', '0002_standalonetask_results_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalonetaskresult',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Чей результат'),
        ),
    ]
